gd <- read.csv("getdata_data_ss06hid[1].csv")
getwd()
gd <- read.csv("getdata_data_ss06hid.csv")
dim(gd)
stsplit(names(gd))[123]
strsplit(names(gd))[123]
strsplit(gd, names)
varnames <- strsplit(gd, "wgtp")
varnames <- strsplit(names(gd), "wgtp")
varnames[[123]]
fileurl <- "https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FGDP.csv"
f <- filepath(getwd(), "getdata.csv")
f <- file.path(getwd(), "getdata.csv")
download.file(fileurl,f)
getdata <- read.csv("getdata.csv")
dim(getdata)
head(getdata)
str(getdata)
names(getdata)
install.packages("data.table")
library(data.table)
dtGDP <- data.table(read.csv(getdata, skip = 4, nrows = 215, stringsAsFactors = FALSE))
summary(getdata)
url <- "https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip"
f <- file.path(getwd(), "project.csv")
download.file(url, f)
project <- read.csv("project.csv")
dim(project)
getwd()
library(reshape2)
f<- file.path(getwd(), "project.zip")
download.file(url, f)
unzip(project.zip)
unzip("project.zip")
Labels <- read.table("UCI HAR Dataset/activity_labels.txt")
Labels
Labels[,2] <- as.character(activityLabels[,2])
Labels[,2] <- as.character(Labels[,2])
Labels[,2]
features <- read.table("UCI HAR Dataset/features.txt")
features[,2] <- as.character(features)
features[,2] <- as.character(features[,2])
features[,2]
requiredfeatures <- grep(".*mean.*|.*std.*", features[,2])
requiredfeatures.names <- features[requiredfeatures,2]
requiredfeatures.names <- gsub('-mean', 'mean', requiredfeatures.names)
requiredfeatures.names <- gsub('-std', 'std', requiredfeatures.names)
requiredfeatures.names <- gsub('[-()]', '', requiredfeatures.names)
#download the datasets
train <- read.table("UCI HAR Datset/train/X_train.txt")
train <- read.table("UCI HAR Datset/train/X_train.txt")[requiredfeatures]
train <- read.table("UCI HAR Dataset/train/X_train.txt")
dim(train)
trainact <- read.table("UCI HAR Datset/train/Y_train.txt")
trainact <- read.table("UCI HAR Dataset/train/Y_train.txt")
trainsub <- read.table("UCI HAR Dataset/train/subject_train.txt")
trainact
dim(trainact)
dim(trainsub)
train <- cbind(trainsub, trainact, train)
dim(train)
head(train)
#download test datasets
test <- read.table("UCI HAR Dataset/test/X_test.txt")
test <- read.table("UCI HAR Dataset/test/X_test.txt")[requiredfeatures]
dim(test)
head(test)
testact <- read.table("UCI HAR Dataset/test/Y_test.txt")
dim(testact)
head(testact)
testsub <- read.table("UCI HAR Dataset/test/subject_test.txt")
test <- cbind(testsub, testact, test)
#merge all datasets
alldata <- rbind(train, test)
train <- read.table("UCI HAR Dataset/train/X_train.txt")[requiredfeatures]
train <- cbind(trainsub, trainact, train)
alldata <- rbind(train, test)
colnames <- c("subject", "activity", requiredfeatures.names)
str(colnames)
head(Labels[,1])
head(labels[,2])
head(Labels[,2])
head(colnames)
allData$activity <- factor(alldata$activity, levels = Labels[,1], labels = labels[,2])
allData$activity <- factor(alldata$activity, levels = Labels[,1], labels = Labels[,2])
alldata <- colnames
allData$activity <- factor(alldata$activity, levels = Labels[,1], labels = Labels[,2])
alldata$activity <- factor(alldata$activity, levels = Labels[,1], labels = Labels[,2])
colnames(alldata) <- c("subject", "activity", requiredfeatures.names)
alldata$subject <- as.factor(alldata$subject)
alldata <- rbind(train, test)
dim(alldata)
colnames(alldata) <- c("subject", "activity", requiredfeatures.names)
alldata$activity <- factor(alldata$activity, levels = Labels[,1], labels = Labels[,2])
alldata$subject <- as.factor(alldata$subject)
dim(alldata)
head(alldata)
alldata.melted <- melt(alldata, id = c("subject", "activity"))
head(alldata.melted)
dim(alldata.melted)
alldata.mean <- dcast(alldata.melted, subject+activity ~variable, mean)
head(alldata.mean)
dim(alldata.mean)
write.table(alldata.mean, "tidy.txt", row.names = FALSE, quote = FALSE)
save(file = getwd(), "run_analysis.R")
save(file = "d:/downloads/run_analysis.RData")
save(file = "C:/users/Nikhilanantha/Downloads/run_analysis.RData")
load("C:/Users/Nikhilanantha/Downloads/run_analysis.RData")
save.image("C:/Users/Nikhilanantha/Downloads/run_analysis.RData")
savehistory("C:/Users/Nikhilanantha/Downloads/run_analysis.RData")
load("C:/Users/Nikhilanantha/Downloads/run_analysis.RData")
load("C:/Users/Nikhilanantha/Downloads/run_analysis.RData")
